### PR TITLE
adds vertical spacing to project listing on both home and project page

### PR DESCRIPTION
**Pull request by htadeusiak**
#761

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Can I see before and after screenshots please?

**Comment by htadeusiak** [comment]
Yes sorry...
Before Projects page:
screen shot 2019-01-22 at 12 27 40 pm
After Projects Page:
screen shot 2019-01-22 at 12 24 47 pm
Before Home Page:
screen shot 2019-01-22 at 12 29 46 pm

After Home Page:
screen shot 2019-01-22 at 12 24 37 pm

**Comment by jonfroehlich** [comment]
How about on individual member pages?

**Comment by jonfroehlich** [comment]
Thanks!

**Pull request merged**
