### PR TITLE
Projects and videos isotope implementations, also fixes isotope sidebar

### LINKED ISSUE #280: Add In Video Types and Have This Be a Group by Feature
- Research Project
- Talk
- Instructional
- Other?

### LINKED ISSUE #315: Project Gallery Filters Have To Be Hooked Up
The project gallery filters have to be hooked up (see circled part below), which includes:

- Writing some backend code that associates primary keywords with each project
- Auto-filling the area and technology sidebar
- Hooking up the filter so that when selected, the list of projects is auto-filtered. We should use isotope for filtering imo: https://isotope.metafizzy.co/filtering.html

image

### PR DESCRIPTION
**Pull request by ShivenBhatt**
fixes #315, fixes #280.
Fixes the issue where the isotope sidebar would go underneath the footer. Now the sidebar stops scrolling when it reaches the bottom of it's isotope grid.
old:
image
new:
image

Also combines implementations of videos and projects for isotope, seen in #507 and #508.
Also updates the isotope readme to accurately reflect the current isotope implementation.

### CODE REVIEW

**Comment by johnsonkuang** [comment]
Tested everything worked

**Comment by jonfroehlich** [comment]
This doesn't actually work on the makeabilitylab-test. 

```
Uncaught SyntaxError: missing ) after argument list
(index):85 False
3isotope-filterBar.js:57 Uncaught TypeError: el.getBoundingClientRect is not a function
    at offset (isotope-filterBar.js:57)
    at handleFilterBarClick (isotope-filterBar.js:76)
    at HTMLAnchorElement.<anonymous> (isotope-init.js:97)
    at HTMLAnchorElement.dispatch (jquery.min.js:3)
    at HTMLAnchorElement.v.handle (jquery.min.js:3)
```
@johnsonkuang, once you merge and the new code gets deployed to the server, you need to also test on the server.

**Comment by ShivenBhatt** [comment]
Code doesn't seem to be on the server. Old js scripts are still running.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ShivenBhatt** [comment]
looks like it was a problem with the file path. Server was looking in /static/ when it should have been looking in website/static

**Pull request merged**
