### PR TITLE
adds 20px of whitespace between project rows

### LINKED ISSUE #466: Increase vertical whitespace between project rows on landing page
image

There should be increased whitespace (maybe ~10 pixels) beneath the title of a project and the next row

### PR DESCRIPTION
**Pull request by htadeusiak**
fixes #466

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Could you post some before and after screenshots at different window widths?

**Comment by jonfroehlich** [comment]
Why doesn’t the production site have this problem?

**Comment by htadeusiak** [comment]
Here is a screenshot of the html for the production site, you'll see the div element has "style=margin-bottom: 20px;"
screen shot 2018-12-29 at 1 32 35 pm



Where as the test site does not have this, but rather has the class "individual-product-listing". With my most recent pr I added "margin-bottom: 20px" to that class and solved that issue.
screen shot 2018-12-29 at 1 32 19 pm

When I get back from break we were going to discuss about how to go about cleaning up the css of the website. #664

**Comment by jonfroehlich** [comment]
Thanks!

**Pull request merged**
