### PR TITLE
Update URL references for members

### PR DESCRIPTION
**Pull request by aileenzeng**
Resolves issues #121, #358 and #362 (although changes originally made for #362 were scrapped).

Members are now accessed by their full name (EX: Page for Foo Bar --> `member/foobar`). I still ended up creating the `url_name` field to make this change because Django urls have to query a field. However, `url_name` is now set automatically and cannot be changed through the admin interface.

There are a few things that need to happen if this gets merged:
1. Accept pull request #379 -- this hopefully fixes database problems from updating `models.py`
2. After the pull request is made, run `docker run -ti -v database:/code/db -v $(pwd)/media:/code/media --entrypoint=python makeability manage.py updateurls`. This command only needs to be used once and should update all the `url_name` field for all existing members in the database. This has worked locally for me, but I'm not sure how it'll work on production/how accessing the database is different. 

The expected error message if step 2 isn't run is: `Reverse for 'member' with arguments '('',)' and keyword arguments '{}' not found. 2 pattern(s) tried: ['member/(?P<member_id>[-a-z]+)/$', 'member/(?P<member_id>[0-9]+)/$']`

### CODE REVIEW

**Comment by aileenzeng** [comment]
Before merging w/ master, we also need to figure out how to run one-time commands on production.

**Comment by jonfroehlich** [comment]
And we only need to run this command on old installs of the makeability lab website, right? It will not need to be run in the future for people who start developing after this has been rolled into master?

**Comment by aileenzeng** [comment]
Yup! It's just a one-time use command (in the future, `url_name`s will be generated as we create new people). We also need to run it on the production site to fill out the `url_name` for existing members.

**Comment by jonfroehlich** [comment]
When the time comes, we'll have to talk to @mechanicjay about how to run one-time commands on production.

**Comment by jonfroehlich** [comment]
Just went through the code. Looks very nice. Testing now.

**Comment by jonfroehlich** [comment]
Hrmph. I can't seem to get the docker command to work.

```
makeabilitylabwebsite jonf$ docker run -ti -v database:/code/db -v $(pwd)/media:/code/media --entrypoint=python makeability manage.py updateurls
Unknown command: 'updateurls'
Type 'manage.py help' for usage.
```
And I verified that I'm on the right branch:
```
commands jonf$ git status
On branch update-url-references
Your branch is up to date with 'origin/update-url-references'.
```
And I verified that the updateurls.py command is there:
```
commands jonf$ pwd
/Users/jonf/Git/makeabilitylabwebsite/website/management/commands
commands jonf$ ls -al
total 80
drwxr-xr-x  8 jonf  staff    256 Jul 13 10:04 .
drwxr-xr-x  6 jonf  staff    192 Jul 13 10:06 ..
-rw-r--r--  1 jonf  staff      0 Oct 24  2017 __init__.py
drwxr-xr-x  5 jonf  staff    160 Nov  6  2017 __pycache__
-rw-r--r--  1 jonf  staff  16751 Oct 24  2017 importpubs.py
-rw-r--r--  1 jonf  staff  11786 Oct 24  2017 importtalks.py
-rw-r--r--  1 jonf  staff    798 Oct 24  2017 modifyprojectpeople.py
-rw-r--r--  1 jonf  staff    573 Jul 13 10:04 updateurls.py
```

I'm clearly doing something wrong... but what?! :)

**Comment by aileenzeng** [comment]
Hmmm odd - it seems to be working for me. Could you paste what happens when you run `docker images` and `docker ps -a` for me?

**Comment by aileenzeng** [comment]
I think this should solve the problem. (You'll also need to pull since I just made a small change)

Run these commands
```
docker build . -t makeability
docker run -ti -v database:/code/db -v $(pwd)/media:/code/media --entrypoint=python makeability manage.py updateurls
docker build . -t makeability
docker run -p 8000:8000 -ti -v database:/code/db -v $(pwd)/media:/code/media -v $(pwd)/website:/code/website makeability
```

Or if you're using make, you can use these:
```
make build
docker run -ti -v database:/code/db -v $(pwd)/media:/code/media --entrypoint=python makeability manage.py updateurls
make run
```

**Comment by jonfroehlich** [comment]
So, I was able to run `updateurls` correctly now. Yay! However, I still can't get the url to work--at least not for my name.

image

Even though I exist:
image

However, it does seem to work for new people that I add.

image

Not sure why this is. It might be because of `importpubs` weirdness as that's how I bootstrapped my content. So, I'm going to merge this and then we'll see if there is a problem on the test server.

**Comment by aileenzeng** [comment]
@jonfroehlich Does `http://0.0.0.0:8000/member/jonfroehlich` work? (Also did you get `http://0.0.0.0:8000/jonfroehlich` from a link? (If so, then this is some HTML bug, oops!)

I'm expecting lots of stuff to be broken for now (since we haven't been able to run the `updateurls` command, and people are referenced by their names (rather than IDs). For example, if you were to click your own name from a publication, it'd direct to `/member/jonfroehlich`.

**Comment by mechanicjay** [comment]
I just tried running this for the test system, but it failed pretty hard.

```
System check identified some issues:

WARNINGS:
website.News.project: (fields.W340) null has no effect on ManyToManyField.
website.Poster.authors: (fields.W340) null has no effect on ManyToManyField.
website.Project.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Project.project_umbrellas: (fields.W340) null has no effect on ManyToManyField.
website.Project.sponsors: (fields.W340) null has no effect on ManyToManyField.
website.Project_umbrella.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Publication.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Publication.project_umbrellas: (fields.W340) null has no effect on ManyToManyField.
website.Publication.projects: (fields.W340) null has no effect on ManyToManyField.
website.Talk.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Talk.project_umbrellas: (fields.W340) null has no effect on ManyToManyField.
website.Talk.projects: (fields.W340) null has no effect on ManyToManyField.
website.Talk.speakers: (fields.W340) null has no effect on ManyToManyField.
Updating urls...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: website_person

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/website/management/commands/updateurls.py", line 9, in handle
    for person in Person.objects.all():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: website_person
```

**Comment by jonfroehlich** [comment]
Thanks @mechanicjay. I think the problem is that, for some reason, the command from the command line is trying to use sqlite rather than PostgreSQL (so it's not finding the website_person table but I would suspect that it wouldn't find _any_ table because none exist).

The server knows to use PostgreSQL because of a local config file. We need to force the command line stuff to use that too..

**Comment by mechanicjay** [comment]
right!  Okay, 

I just got a shell in the container and ran the command to be sure all the environment stuff was right and I'm getting errors.    I think we're in the situation again where the database is a different state than the code thinks it is.  

```
website.News.project: (fields.W340) null has no effect on ManyToManyField.
website.Poster.authors: (fields.W340) null has no effect on ManyToManyField.
website.Project.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Project.project_umbrellas: (fields.W340) null has no effect on ManyToManyField.
website.Project.sponsors: (fields.W340) null has no effect on ManyToManyField.
website.Project_umbrella.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Publication.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Publication.project_umbrellas: (fields.W340) null has no effect on ManyToManyField.
website.Publication.projects: (fields.W340) null has no effect on ManyToManyField.
website.Talk.keywords: (fields.W340) null has no effect on ManyToManyField.
website.Talk.project_umbrellas: (fields.W340) null has no effect on ManyToManyField.
website.Talk.projects: (fields.W340) null has no effect on ManyToManyField.
website.Talk.speakers: (fields.W340) null has no effect on ManyToManyField.
Updating urls...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column website_person.url_name does not exist
LINE 1: ...son"."middle_name", "website_person"."last_name", "website_p...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/website/management/commands/updateurls.py", line 9, in handle
    for person in Person.objects.all():
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column website_person.url_name does not exist
LINE 1: ...son"."middle_name", "website_person"."last_name", "website_p...
```

**Comment by mechanicjay** [comment]
@aileenzeng I think I really broke something.   The site is returning 500 errors, even after rebuilding....I'm trying to figure it out...

**Comment by mechanicjay** [comment]
Okay, I connected directly to the database and added the url_name column, which resolved the 500 error.

  I was then able to run the updateurls command without issue. 

So it should be working now?

**Comment by aileenzeng** [comment]
It was working for a little bit, but I'm got this (very briefly on the home page for makeabilitylab-test):
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server
```

(Update: the front page seems to work fine now)

And a Server Error 500 on https://makeabilitylab-test.cs.washington.edu/people/

**Comment by mechanicjay** [comment]
@aileenzeng Is it possible that the modifyprojectpeople migration needs to be run as well?

**Comment by aileenzeng** [comment]
@mechanicjay Hmm I'm not familiar with this migration. Could you elaborate more?

**Comment by mechanicjay** [comment]
@aileenzeng when I run `python manage.py`  It lists a bunch of stuff, under the [website] heading the updateruls thing is the last in the list, modifyprojectpeople is just above that.

**Comment by aileenzeng** [comment]
@mechanicjay I don't think so - it looks like a pretty old one-time use command (it shouldn't affect `url_name` stuff)

**Comment by mechanicjay** [comment]
@aileenzeng The debug.log is full of errors that I don't understand...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [pdf_file] in 'None'
DEBUG 2018-07-13 18:17:26,077 base 127 140243474827008 Exception while resolving variable 'pdf_file' in template 'website/index.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 879, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 887, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'pdf_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 894, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'pdf_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [pdf_file] in 'None'
```
And so forth...

**Comment by mechanicjay** [comment]
Okay, I just stepped through the different commits to master today, rebuilding the image each time, and commit d283336e96692bf50c2cddfaa3bf5fa2e8781481 is where the site starts throwing 500 errors on the /people /news /publications pages.

**Comment by aileenzeng** [comment]
@jonfroehlich Yeah - I'm looking into the debug logs right now. I've got one idea so far:

This error keeps popping up: 
`django.core.urlresolvers.NoReverseMatch: Reverse for 'member' with arguments '('victorde souza',)' and keyword arguments '{}' not found. 2 pattern(s) tried: ['member/(?P<member_id>[-a-z]+)/$', 'member/(?P<member_id>[0-9]+)/$']`

I think this is because Victor has a space in his last name, which is causing his `url_name` to become `victorde souza` rather than `victordesouza`. I'll see if automatically stripping spaces fixes the problem.

I also realized that I forgot to reference people by their url_name on the landing page, so I'm going to push a separate commit to address that as well.

**Comment by jonfroehlich** [comment]
Oh wow, good catch Aileen. I hope this works.

**Pull request merged**
