### PR TITLE
Changes mouseover on headshots

### LINKED ISSUE #674: Change mouseover on headshots
Change mouseover on headshots so that the "easter egg" headshot is only shown when the name is moused over rather than the photograph itself. Will make it easier to copy images in the future (e.g., into slide decks, posters).

image

### PR DESCRIPTION
**Pull request by htadeusiak**
fixes #674 

I felt this issue was best solved by adding some jQuery. I created a new file called peopleMouseoverFix.js. Do you typically create a new js file for something like this or add it to an existing one?

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Hi Hank,

This is great progress! Can you split this PR into multiple PRs with roughly one per Issue. 

That is:the headshot stuff should be in its own PR. 

Jon

**Comment by htadeusiak** [comment]
The last commit should have taken out the code affecting the news titles. So this pull request should only affect the headshot stuff. Correct me if I am wrong though.

**Comment by jonfroehlich** [comment]
Ah. Ok. I’m mobile right now.

**Comment by jonfroehlich** [comment]
This branch now has a conflict, can you fix @htadeusiak?

**Comment by htadeusiak** [comment]
Fixed

**Pull request merged**
