### PR TITLE
Resolves #411: Add favicon to main and admin pages

### LINKED ISSUE #411: Add favicon?
I was thinking it would be nice if we had a favicon for the site. This is sort of what I was thinking:
Current:
image

One possibility:
image

Thoughts?

### PR DESCRIPTION
**Pull request by aileenzeng**
Fixes #411 

Summary of changes:
* Created a favicon (using a favicon generator) -- unfortunately, it fit the logo to a square (rather than keeping its dimensions). 
* Added favicon to the main website and admin pages

| Before | After |
| ------ | ------ |
| image | image |
| image | image |

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Ugh, I don't think we can use this. We have to maintain the proper dimensions of the logo. This one looks squeezed horizontally... what was the favicon generator you used?

**Comment by jonfroehlich** [comment]
Can’t you just make a square version of logo by adding appropriate whitespace and then uploading that? Should be fast to do

**Comment by aileenzeng** [comment]
@jonfroehlich Ooh good idea - hadn't thought of that :) 

Here's what it looks like now:
image

image

**Comment by jonfroehlich** [comment]
Woohoo. Looks great!

**Pull request merged**
