### PR TITLE
fixes the landing page (#448, #447, #441)

### LINKED ISSUE #448: Project layout breaks on landing page on page resize
Correct:
image

Then as I shrink window, thumbnails collide and overlap:
image

Note that the Recent Videos part of the webpage seems to do what we want, so possibly adopt that approach?

### PR DESCRIPTION
**Pull request by ShivenBhatt**
fixes bugs with the landing page.
# Looked like this:
image
image

# Now looks like this:
image
image
image
image

Made some style changes to index.html

### CODE REVIEW

**Comment by jonfroehlich** [comment]
When I try to run this branch, I get:

```
System check identified 13 issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f61ad7ac7b8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/website/migrations/0006_auto_20180717_1736.py", line 9, in <module>
    class Migration(migrations.Migration):
  File "/code/website/migrations/0006_auto_20180717_1736.py", line 43, in Migration
    field=models.ForeignKey(blank=True, default=website.models.get_person, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Advisor', to='website.Person'),
AttributeError: module 'website.models' has no attribute 'get_person'
```

I think this is related to code @johnsonkuang wrote...

**Comment by ShivenBhatt** [comment]
I just made changes to index.html... so yeah. I'll talk to @johnsonkuang about getting this fixed, hopefully get you these fixes tomorrow.

**Comment by jonfroehlich** [comment]
Thanks

**Comment by ShivenBhatt** [comment]
Ok, so Johnson isn't here yet, but when I cloned the website and tried to make migrations, I got this:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Program Files\Python3.6\lib\site-packages\django\core\management\__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "C:\Program Files\Python3.6\lib\site-packages\django\core\management\__init__.py", line 324, in execute
    django.setup()
  File "C:\Program Files\Python3.6\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Program Files\Python3.6\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Program Files\Python3.6\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Program Files\Python3.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
```
I'm pretty sure this is related to the rest API johnson was making, except it's either unfinished or broken. I suggest rolling back commits on the master until it works, then starting from there. No point in building further on a broken master.

**Comment by jonfroehlich** [comment]
Master is not broken. Works for me.

**Comment by ShivenBhatt** [comment]
Hmm, that's odd. The last commit that worked for me was before update-django-and-js. Maybe my error has something to do with not having the right requirements. But when I do pip install, it says that I DO have the right requirements. I think I'll delete my old installations, and then reinstall.

**Pull request closed without merging**
