### PR TITLE
Member Page Update

### LINKED ISSUE #694: Fix top of member.html
Lots of things wrong:

- [x] Remove banner
- [x] When at top of page in non-scroll position, make menu bar white, text black, and ml logo black
- [x] Change all icons (e.g., twitter, mail icon) to be black
- [x] Fix web link icon so that it's not showing the little text at the bottom or find a different icon to use
- [ ] I don't like how the bio information is shown. What to do with this? Just in general this whole headshot -> name + links -> bio feels weird in its layout and design

image

### PR DESCRIPTION
**Pull request by htadeusiak**
fixes #694 
Now has updated web link and twitter icons. White nav bar in non-scroll position. New page design.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
This branch has conflicts that need to be resolved before merging--can you review and do so?

**Comment by htadeusiak** [comment]
Yes on it

**Comment by jonfroehlich** [comment]
Nice job on this. Your edits to css really make me think of: https://github.com/jonfroehlich/makeabilitylabwebsite/issues/664. It's such a complete mess right now. As you gain more familiarity with the site and gain expertise with CSS, we should sit down and discuss how to refactor the CSS to improve the CSS architecture and organization overall, improve code readability and debuggability, and reduce redundancy.

**Comment by htadeusiak** [comment]
So meet up when I get back in town and discuss/start on #664 ?

**Pull request merged**
