### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by johnsonkuang**
Merging the Windows readme back into the main readme

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Thanks for this. There are a few typos--can you fix them (e.g., instrucations).

**Comment by ShivenBhatt** [comment]
i'll fix it

**Comment by ShivenBhatt** [comment]
i fixed it

**Comment by ShivenBhatt** [comment]
@jonfroehlich, the unit testing documentation is on a separate branch, I'll make a pull request for it.

**Pull request merged**
