### PR TITLE
removes 'recent news' and 'quick info' in project page on mobile

### LINKED ISSUE #750: Project pages on mobile
Project pages on mobile don't look great: for one thing, your greeted by Quick Info and Recent News rather than About. The quick fix for this should be just to hide these things on mobile screens (that is, to be clear: hide Quick Info and Recent News) so that About is immediately visible just after the header.

image

### PR DESCRIPTION
**Pull request by htadeusiak**
fixes #750 

What 's the best way to test this. Is it just to push it to the test server and see from there?

### CODE REVIEW

**Comment by htadeusiak** [comment]
Just figured out a way. Do not merge yet, I need to edit/fix it.

**Comment by htadeusiak** [comment]
Sorry about the mess of commits. I'm still learning git/github. publications.css is unaffected, there is just the weird spacing reformatting that pycharm does. Should be good to merge.

**Comment by jonfroehlich** [comment]
No problem. Thanks for the explanation. Can I see some before and after animated gifs please? Thanks!

**Comment by htadeusiak** [comment]
I feel like a before was not necessary, the recent news and quick info don't disappear.
After:
resize
After pic on iphone 6/7/8 plus:
screen shot 2019-01-12 at 4 57 21 pm

**Pull request merged**
