### PR TITLE
Resolves #374 added news listing module

### LINKED ISSUE #374: Need to update news
Now that we are starting to get somewhere in our transition from UMD to UW servers for the ML website, we need to update the news feed. I'd like to retrospectively add all major news items that have occurred since Oct 18, 2017 (including paper acceptances, awards, new lab members, new coverage, new funding, etc. etc.).

### PR DESCRIPTION
**Pull request by johnsonkuang**
Complete with pagination and links (to individual newspages and authors)

1.  Added a new page to the website which lists out the news objects in reverse chronological order.
2.  Linked the new page to the base.html
3.  Objects posted within a 24 hour time-span will have their date displayed as "X hours ago" (can be adjusted via the time_diff method set in the news model in models.py)
4. Amount of objects can be adjusted by changing the initial instatiation `paginator = Paginator(news_list, 10)`, currently set at 10

# Screenshot of the new page
[Image from Gyazo](https://gyazo.com/836db23751285eb147254dd05158ff43)

### CODE REVIEW

**Comment by aileenzeng** [comment]
I think there's an issue with the test site not updating everything properly (I don't see changes from #403 yet). Maybe we can wait to see if #403 breaks the site. If it does, we could try merging #379 to make sure that it works properly. I had a chance to test it out once (and it did work!), but I had trouble replicating the issue later on.

**Comment by mechanicjay** [comment]
@aileenzeng In my investigation of why jon was not getting emails, I recently found your suspicion to be true.  I *THINK* I have it all working properly now -- including running a fresh pull of master.

Sorry for the trouble!

**Comment by aileenzeng** [comment]
@mechanicjay Hooray!! Thanks :)

**Comment by jonfroehlich** [comment]
@johnsonkuang, can you do the following:

- Remove .gitignore and all .idea/* files from this commit
- Why did you rename 'projects/images/' to 'project/images/' in models.py?
- Please add a comment in models.py for why you switched the DateField to DateTimeField for News
- why did you add ?version=1 to index.hml stylesheet statement?
- to be more consistent with other pages, rather than calling this news-listing, can you just call it news? So you would have news.css, and news.html, etc.
- remove website/templates/website/projects.html from this commit
- remove anything to do with test cases from this commit (e.g., test_images.py, test_person.py, etc. etc.). this should all go into a different branch and PR

**Comment by johnsonkuang** [comment]
@jonfroehlich 
To address the bullet points 3-5

- Change to a DateTimeField in the News model would allow the display of objects posted within a certain timeframe as "X hours ago". Django will default to 00:00:00 if it is only a DateField. A DateTimeField helps track the hour which this news object was posted and can be used to display such info to the UI.
- `?version=1` is version control and helps force a refreshing of the static files in the browser to ensure that changes in any static file will be registered
- there is already a news template and news.css, therefore the main landing page could not be named news.html and news.css likewise cannot be used for news-listing

**Comment by jonfroehlich** [comment]
Thanks. A few follow-ups plus you didn't answer all of my questions.

> Change to a DateTimeField in the News model would allow the display of objects posted within a certain timeframe as "X hours ago". Django will default to 00:00:00 if it is only a DateField. A DateTimeField helps track the hour which this news object was posted and can be used to display such info to the UI.
Sorry, yes, I know why you did this--you told me in person. I meant to indicate that you should document this change with comments in the code itself.

> ?version=1 is version control and helps force a refreshing of the static files in the browser to ensure that changes in any static file will be registered
But why do we need to do this? Why make this change now?

> there is already a news template and news.css, therefore the main landing page could not be named news.html and news.css likewise cannot be used for news-listing
Got it. Thanks.

> Why did you rename 'projects/images/' to 'project/images/' in models.py?
You forgot to answer this.

**Comment by johnsonkuang** [comment]
Oh that was an accident I'll change it back

**Comment by johnsonkuang** [comment]
@jonfroehlich all issues have been resolved

**Comment by jonfroehlich** [comment]
Thanks. But you are still not responding to my questions here: https://github.com/jonfroehlich/makeabilitylabwebsite/pull/408#issuecomment-404906260.

**Comment by jonfroehlich** [comment]
In order for this to work, you must shutdown the existing server and rerun using `make run` because models.py is updated (so db migrations are necessary)

**Comment by jonfroehlich** [comment]
I'm gonna merge this for now... and we can continuing discussing https://github.com/jonfroehlich/makeabilitylabwebsite/pull/408#issuecomment-404906260 on this thread.

**Pull request merged**
