### PR TITLE
CSS Cleanup Part 1 and 2

### PR DESCRIPTION
**Pull request by htadeusiak**
#664 
I removed any unused CSS and did a quick clean up of the CSS style. 

I know I recommend using UnCSS in my report. However, I found that UnCSS had some issues parsing our html because of Django. I instead used another tool called PurifyCSS and that did the trick. I then ran the CSS through CSS Lint to fix some of the basic styling errors.

All the CSS files have been modified to 2 space indents. This is a very common practice for CSS and recommended by [Harry Roberts](https://cssguidelin.es/#the-importance-of-a-styleguide) (he's included in my report), 
"At a very high-level, we want
    - two(2) space indents, no tabs;
    - 80character wide columns;
    - multi-line CSS;
    - meaningful use of whitespace.
But, as with anything, the specifics are somewhat irrelevant—consistency is key."

The next move would be installing a preprocessor and reorganizing the CSS files, but I know you want to talk more in depth about that.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Thanks Hank. How do you propose we test this?

**Comment by htadeusiak** [comment]
I would suggest having localhost:8000 and the Makeability test website up in your browser. Then go page by page comparing any differences.

**Comment by jonfroehlich** [comment]
Looks good overall but we shouldn't be using the Adelle font anymore.

Also, this branch now has a merge conflict. Can you fix?

**Comment by htadeusiak** [comment]
Yes, can I open a new issue for the Adelle font after we merge this?

**Comment by jonfroehlich** [comment]
Yep

**Pull request merged**
