### PR TITLE
Changed README for new Docker structure

### PR DESCRIPTION
**Pull request by johnsonkuang**
Updated the README with information about the new docker system implemented in #807.
Deleted the makefile because the new system is much simpler to use.

### CODE REVIEW

**Comment by johnsonkuang** [comment]
The changes to `models.py` was to remove a test field added previously.

The changes to the .gitignore have been removed, as well as index.html

The read-me should be fixed as well now.

**Comment by jonfroehlich** [comment]
Oops, @johnsonkuang can you resolve the merge conflict here? And then just merge. Thanks.

**Comment by jonfroehlich** [comment]
@johnsonkuang can you please resolve the merge conflicts here in docker-compose.yml so I can merge this?

**Comment by jonfroehlich** [comment]
I couldn't get this to merge correctly and @johnsonkuang wasn't responsive to my requests... so I just manually moved the desired files into master and committed them.

**Pull request closed without merging**
