### PR TITLE
Long photo captions get cutoff

### PR DESCRIPTION
**Pull request by DDaiJ**

### CODE REVIEW

**Comment by htadeusiak** [comment]
#691 
^^Just for future reference you should try and link the pr request to the issue like so.
It just makes it easier.

It looks good. I don't think we want the added meta tag in base.html though. What was the reason you added it?

**Comment by DDaiJ** [comment]
Oh, that's because the css couldn't be updated so I searched it on google and that's one of the methods I tried to make it work. If you don't think it's necessary, feel free to delete it.

**Comment by jonfroehlich** [comment]
Why couldn’t the css be updated? I’m confused.

**Comment by htadeusiak** [comment]
It was cached on her browser

**Comment by DDaiJ** [comment]
I just deleted meta I added on base.html. Yes, because of the cache. It worked later.

**Comment by jonfroehlich** [comment]
This is super common. Just hold Ctrl-refresh or cmd-refresh

**Comment by htadeusiak** [comment]
Jon I know your really busy right now, but I've tested it and it looks good so I'm going to go ahead and merge it.

**Pull request merged**
