### PR TITLE
Adjust sidebar scrolling limitations to accommodate for footer.

### PR DESCRIPTION
**Pull request by alexjk38**
With the newly created footer for the UW makeabilitylab website, extra adjustments had to be made for the sidebar in order to prevent one from overlapping the other. In this case the sidebar was being hidden under the footer after a certain point in scrolling.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
@alexjk38, do you have a before and after for this? Or a link to the Issue? Then one of us will review.

**Comment by alexjk38** [comment]
Before: https://cl.ly/1f090L04111T
After: https://cl.ly/1n2o0W0V0u33

**Comment by jonfroehlich** [comment]
@alexjk38, thanks for making those changes. Does this PR address an open ticket? If so, can you link to it? Because I'm not even really sure I understand what you're fixing here... even with the video examples. 

After you've done that, @johnsonkuang, can you review this PR?

**Comment by alexjk38** [comment]
Sorry about that, the Issue addressed is #412

**Comment by jonfroehlich** [comment]
Thanks. @johnsonkuang, can you test and then merge, if it works. :)

**Comment by jonfroehlich** [comment]
@johnsonkuang, ping! I'd like you to review this as part of our push towards deployment.

**Comment by johnsonkuang** [comment]
Will do once my own pr is done

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by johnsonkuang** [comment]
works, merging PR

**Pull request merged**
