### PR TITLE
fixed #626

### LINKED ISSUE #626: Fix alignment of title/caption on about image on project pages
image

### PR DESCRIPTION
**Pull request by higherdefender**

### CODE REVIEW

**Comment by jonfroehlich** [comment]
This is already fixed. :) sorry, I fixed it on the plane and didn’t update the issue because I didn’t have internet.

**Comment by higherdefender** [comment]
oh, but the title images on project page still looks weird. Did you deploy
your changes?

**Comment by higherdefender** [comment]
[image: image.png]

**Comment by jonfroehlich** [comment]
A couple of things:
1. Your image screenshot didn't come through
2. Did you check ml-test? That's where all code is deployed to until it's tested and verified. See: https://github.com/jonfroehlich/makeabilitylabwebsite#deploying-code-to-uw-servers

**Comment by higherdefender** [comment]
It works on ml-test. I consider this issue closed.

**Comment by jonfroehlich** [comment]
Great, thanks Dhruv. Love that you're trying to contribute to dev effortson the ml website--would be great to get you working on the footer issue https://github.com/jonfroehlich/makeabilitylabwebsite/issues/571

**Pull request closed without merging**
