### PR TITLE
Create README_WINDOWS.md

### PR DESCRIPTION
**Pull request by johnsonkuang**
Generated new instructions for the readme with docker and manual installation instructions.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Thanks for your work on this @johnsonkuang. Is there any reason why this isn't simply integrated into the main readme.md? IMO, there shouldn't be any reason why the Mac receives more emphasis or priority over Windows.

My suggestion would be to integrate this into the primary readme.md with appropriate sub-headers.

**Comment by johnsonkuang** [comment]
It's not a problem @jonfroehlich, the reason before was that there are quite a lot of differences between the mac and windows commands so we decided that it would be better to just give windows its own set of instructions for clarity purposes. But I can merge it into the main readme anyway.

**Comment by jonfroehlich** [comment]
Please make *separate* sections using sub-headers. So, for example, you have a header1 that is: "Setup Instructions Mac" and a header1 that is "Setup Instructions Windows" or something similar. Make sense?

**Comment by johnsonkuang** [comment]
Got it I will make the appropriate changes

**Pull request closed without merging**
