### PR TITLE
Adding import commands

### PR DESCRIPTION
**Pull request by johnsonkuang**
Before, we used bibtex and parsed it in tandem with the umd server to generate publications and talk objects to populate the database.

Now, we take JSON data that we serialized and transferred using the REST API and automatically deserialize using the Django rest_framework. The deserializer will first take the file urls within the JSON and download the files to a temp directory, then sets the file in the JSON wrapped in a Django File Object. Following, the deserialization will deserialize the Many-to-many objects attached to the object (authors, speakers, etc) and save it to the database.

### CODE REVIEW

**Comment by aileenzeng** [comment]
Yup! 

@johnsonkuang Could you write up some testing instructions? (what commands I'll need to run, what I should look for)

**Comment by johnsonkuang** [comment]
@aileenzeng 
Run the commands as you would with the original and check to see that the objects get saved into the database.

**Comment by jonfroehlich** [comment]
@aileenzeng, I believe I had @johnsonkuang write up instructions on the main readme.md for this repo.

@johnsonkuang: you are assuming that @aileenzeng knows anything about the previous method :P

**Comment by johnsonkuang** [comment]
`docker run -ti -v ${pwd}/db:/code/db -v ${pwd}/media:/code/media --entrypoint=python makelab_image manage.py import<talks or pubs>`. You may have to change `${pwd}` though

**Comment by aileenzeng** [comment]
Okay, I ran the docker command (`docker run -ti -v database:/code/db -v $(pwd)/media:/code/media --entrypoint=python makeability manage.py importpubs
`). I got this:
```
preprocessing data
Evaluating_Angular_Accuracy_of_Wrist-based_Haptic_Directional_Guidance_for_Hand_Movement_nIxCCJA.pdf
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/code/website/management/commands/importpubs.py", line 37, in handle
    with open(file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/code/media/temp/Evaluating_Angular_Accuracy_of_Wrist-based_Haptic_Directional_Guidance_for_Hand_Movement_nIxCCJA.pdf'
```

Running `importtalks` now.

**Comment by johnsonkuang** [comment]
Aileen's issue has been resolved.

**Comment by jonfroehlich** [comment]
@aileenzeng, can you try again?

@johnsonkuang, this branch has conflicts with master, can you fix them?

**Comment by aileenzeng** [comment]
@jonfroehlich Still running importtalks (the PDFs are big so they take a while!) I will make sure to do importpubs as soon as importtalks finish. Johnson fixed the merge conflicts on my computer.

@johnsonkuang Every once in a while, I see warning messages like this during `importtalks`:
```
Talk 'Understanding the Role of Thermography in Energy Auditing: Current Practices and the Potential for Automated Solutions' has just been saved with PDF=/code/media/talks/media/temp/chi2015thermographyv7b-slideshare-150504122635-conversion-gate02.pdf, checking to see if we should auto-generate a thumbnail
   **** Warning: considering '0000000000 XXXXX n' as a free entry.
   **** Warning: considering '0000000000 XXXXX n' as a free entry.
   **** Warning: considering '0000000000 XXXXX n' as a free entry.
```
Is this important/anything to worry about?

**Comment by aileenzeng** [comment]
Finished `importtalks` and got this error when I tried to go to `http://localhost:8000/talks/`:
```
Template error:
In template /code/website/templates/website/base.html, error at line 23
   string index out of range
   13 :     <link rel="shortcut icon" href="{% static 'website/img/ml-favicon.png' %}" />
   14 : 
   15 :     <!-- Load some fonts -->
   16 :     <!-- Raleway: https://fonts.google.com/specimen/Raleway -->
   17 : {#    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />#}
   18 : {#    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Raleway|Roboto" rel="stylesheet">#}
   19 : {#    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Open+Sans:400,700|Raleway:400,800|Roboto:400,700" rel="stylesheet">    #}
   20 : {#    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">#}
   21 :     <!-- Raleway 300 is light, 400 is regular, 500 is medium, 600 is semi-bold, 700 is bold -->
   22 :     <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
   23 :     <link href="https://fo nts.googleapis.com /css?family=Roboto" rel="stylesheet">
   24 : 
   25 :     <link rel="stylesheet" type="text/css" href="{% static 'website/css/bootstrap.min.css' %}"/>
   26 : 
   27 :     <!-- A modified version of the grayscale css -->
   28 :     <link rel="stylesheet" type="text/css" href="{% static 'website/css/grayscale.css' %}"/>
   29 : 
   30 :     <!-- Our custom style sheets -->
   31 :     <link rel="stylesheet" href="{% static 'website/css/carousel_fade.css' %}"/>
   32 :     <link rel="stylesheet" href="{% static 'website/css/base.css' %}"/>
   33 :     <link rel="stylesheet" href="{% static 'website/css/autocomplete.css' %}"/>


Traceback:

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/code/website/views.py" in talks
  278.     return render(request, 'website/talks.html', context)

File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py" in render
  36.     content = loader.render_to_string(template_name, context, request, using=using)

File "/usr/local/lib/python3.7/site-packages/django/template/loader.py" in render_to_string
  62.     return template.render(context, request)

File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render
  175.                     return self._render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  155.             return compiled_parent._render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py" in render
  67.                 result = block.nodelist.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py" in render
  211.                     nodelist.append(node.render_annotated(context))

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in render
  993.             output = self.filter_expression.resolve(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in resolve
  676.                 obj = self.var.resolve(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in resolve
  802.             value = self._resolve_lookup(context)

File "/usr/local/lib/python3.7/site-packages/django/template/base.py" in _resolve_lookup
  864.                             current = current()

File "/code/website/models.py" in get_title
  675.         cap_title = ' '.join(s[0].upper() + s[1:] for s in self.title.split(' '))

File "/code/website/models.py" in <genexpr>
  675.         cap_title = ' '.join(s[0].upper() + s[1:] for s in self.title.split(' '))

Exception Type: IndexError at /talks/
Exception Value: string index out of range
```

I'm still using the same Docker image (didn't rebuild the container). The Docker image when I tried to rebuild ended up being >10GB (which is really big -- I think usually images are generally ~1GB, sometimes less).

**Comment by aileenzeng** [comment]
@johnsonkuang I'm getting this error: `FileNotFoundError: [Errno 2] No such file or directory: '/code/media/temp/media/temp/Evaluating_Angular_Accuracy_of_Wrist-based_Haptic_Directional_Guidance_for_Hand_Movement_nIxCCJA.jpg'` I remember you typing something into my computer that had fixed it, but I can't remember what that was (+ I'm working off a fresh build of the website now, so none of those changes are on my computer anymore)

**Comment by aileenzeng** [comment]
Some more comments:
* I'm able to get past the 'no such file or directory' error (from above) by creating a `media` folder in `media/temp` and by creating a `temp` folder inside that new `media` folder. Is there a reason that we're nesting it inside all these directories? (We end up w/ multiple copies of the PDFs -- one copy is in `/media`, another is in `/media/temp/media`).
* I'm also getting other errors: `FileNotFoundError: [Errno 2] No such file or directory: 'media/person/JonggiHong.jpg'` (not really sure why we need images of all people)

Can't seem to get `importtalks` or `importpubs` to run properly :(

**Comment by jonfroehlich** [comment]
Something is strange with this PR--contains 186 commits and 84 file changes?

**Comment by jonfroehlich** [comment]
@johnsonkuang, I think you're going to have to redo this PR. It currently contains 187 commits and 84 changed files. This can't possibly be right.

**Comment by johnsonkuang** [comment]
closing this PR to fix the commit issue

**Pull request closed without merging**
