### PR TITLE
Added Rich Text Editor - CKEditor

### PR DESCRIPTION
**Pull request by htadeusiak**
#35 
Implements the CKEditor to the admin page for the content section of news articles. There are a lot of plugins that we can use to customize the CKEditor and its functions. Just for right now though, I would like you to take a look at its basic functions. 

As far as implementing it to the test website, I'm not sure what you might have to do(if anything at all). I know on my local dev environment I needed to run <code>python3 manage.py collectstatic</code>to copy required CKEditor media resources into our directories. I also might have ran a line of code when installing 'django-ckeditor' into the docker shell.

Let me know what questions you have or what else you need me to do.

### CODE REVIEW

**Comment by jonfroehlich** [comment]
Can I see some screenshots?

**Comment by htadeusiak** [comment]
I made it so the edited text(bold, color, underline, etc.) and images will not show up in previews of the articles. Rather it will just be the straight text. You can see examples of 'previewing text' when viewing all the news listing on the news page or the "Recent News form [author]" column when you're viewing an individual news article.

**Comment by jonfroehlich** [comment]
Looks awesome. I’m excited to try it. I’m guessing that this will require database scheme updates for image handling etc so we’ll have to work with Jason Howe on it once we finish testing.

**Comment by htadeusiak** [comment]
Yeah sounds good. Like I said earlier, I'm not exactly sure what implementing it to the production sever is going to take. Let me know what you need from me though.

**Comment by johnsonkuang** [comment]
The rich text editor is working:
[Image from Gyazo](https://gyazo.com/b57193e4fd1737a109fc872714636814)

From the screenshot you can see that it saves formatting such as bolding and alignment.

In order to integrate this PR into master, we will need to have Jason run some commands on the server to build the ckeditor module.

**Comment by johnsonkuang** [comment]
We'll have to run `docker-compose build` on the back-end once we've merged this PR

**Comment by jonfroehlich** [comment]
If you're confident this works, can you merge and follow through with Jason then?

**Comment by johnsonkuang** [comment]
Merged into master

**Pull request merged**
